import { useEffect, useState } from "react";
import { Check, Download, FileCheck2, Plus, RefreshCw, Save, Sparkles, Trash2 } from "lucide-react";
import { studentDownload } from "../api/student-auth";
import { generateAtsResume, getGeneratedResume, listGeneratedResumes, loadResumeBuilder, saveResumeBuilder, updateGeneratedResume } from "../api/student-career";
import type { GeneratedResume, ResumeBuilderData, ResumeContent, ResumeEntry } from "../api/student-career";

const input="w-full px-3.5 py-2.5 bg-[#EFF2FA] border-[1.5px] border-transparent rounded-[10px] text-[13px] text-[#0F1C3F] outline-none focus:border-[#1B3A6B] focus:bg-white";
const blank=():ResumeEntry=>({title:"",subtitle:"",start_date:"",end_date:"",location:"",description:"",bullets:[],technologies:[],url:""});

function Entries({label,items,onChange}:{label:string;items:ResumeEntry[];onChange:(x:ResumeEntry[])=>void}){
  const set=(i:number,key:keyof ResumeEntry,value:unknown)=>onChange(items.map((x,n)=>n===i?{...x,[key]:value}:x));
  return <section className="space-y-3"><div className="flex items-center justify-between"><h3 className="text-[14px] font-semibold text-[#0F1C3F]">{label}</h3><button type="button" onClick={()=>onChange([...items,blank()])} className="flex items-center gap-1 text-[11.5px] font-semibold text-[#1B3A6B]"><Plus size={13}/>Add</button></div>{items.map((x,i)=><div key={i} className="p-4 rounded-xl border border-[#E3E8F2] bg-[#FBFCFE] space-y-3"><div className="grid sm:grid-cols-2 gap-3"><input className={input} value={x.title} placeholder={label==="Education"?"Degree / qualification":"Title"} onChange={e=>set(i,"title",e.target.value)}/><input className={input} value={x.subtitle||""} placeholder={label==="Education"?"College / university":"Company / organization"} onChange={e=>set(i,"subtitle",e.target.value)}/><input className={input} value={x.start_date||""} placeholder="Start date" onChange={e=>set(i,"start_date",e.target.value)}/><input className={input} value={x.end_date||""} placeholder="End date / Present" onChange={e=>set(i,"end_date",e.target.value)}/></div><textarea className={input} rows={2} value={(x.bullets||[]).join("\n")} placeholder="Achievements / details — one bullet per line" onChange={e=>set(i,"bullets",e.target.value.split("\n").map(v=>v.trim()).filter(Boolean))}/><div className="flex gap-3"><input className={input} value={(x.technologies||[]).join(", ")} placeholder="Skills / technologies, comma separated" onChange={e=>set(i,"technologies",e.target.value.split(",").map(v=>v.trim()).filter(Boolean))}/><button type="button" aria-label={`Remove ${label}`} onClick={()=>onChange(items.filter((_,n)=>n!==i))} className="px-3 text-red-500"><Trash2 size={15}/></button></div></div>)}</section>;
}

export function AtsResumeBuilder(){
  const [data,setData]=useState<ResumeBuilderData|null>(null);const [versions,setVersions]=useState<GeneratedResume[]>([]);const [current,setCurrent]=useState<GeneratedResume|null>(null);const [target,setTarget]=useState("");const [busy,setBusy]=useState("");const [error,setError]=useState("");const [message,setMessage]=useState("");
  const load=async()=>{const [builder,list]=await Promise.all([loadResumeBuilder(),listGeneratedResumes()]);setData(builder);setVersions(list);if(list[0])setCurrent(await getGeneratedResume(list[0].id));};
  useEffect(()=>{load().catch(e=>setError(e.message));},[]);
  const profile=(key:keyof ResumeBuilderData["profile"],value:unknown)=>setData(x=>x?{...x,profile:{...x.profile,[key]:value}}:x);
  const save=async()=>{if(!data)return;setBusy("save");setError("");try{setData(await saveResumeBuilder(data.profile));setMessage("Resume information saved.");}catch(e){setError(e instanceof Error?e.message:"Unable to save");}finally{setBusy("");}};
  const generate=async()=>{if(!data||!target.trim())return;setBusy("generate");setError("");try{await saveResumeBuilder(data.profile);const result=await generateAtsResume(target.trim());setCurrent(result);setVersions(await listGeneratedResumes());setMessage("ATS-friendly resume generated. Review and edit before downloading.");}catch(e){setError(e instanceof Error?e.message:"Generation failed");}finally{setBusy("");}};
  const updateContent=(key:keyof ResumeContent,value:unknown)=>setCurrent(x=>x&&x.content?{...x,content:{...x.content,[key]:value}}:x);
  const saveGenerated=async()=>{if(!current?.content)return;setBusy("resume");setError("");try{const result=await updateGeneratedResume(current.id,current.title,current.content);setCurrent(result);setVersions(await listGeneratedResumes());setMessage("Resume updated and ATS score recalculated.");}catch(e){setError(e instanceof Error?e.message:"Unable to update resume");}finally{setBusy("");}};
  if(!data)return <div className="py-16 flex justify-center gap-2 text-[13px] text-[#5A6A8A]"><RefreshCw size={15} className="animate-spin"/>Loading resume builder…</div>;
  return <div className="space-y-6"><div><h2 className="text-[21px] text-[#0F1C3F]" style={{fontFamily:"var(--font-serif)"}}>ATS Resume Builder</h2><p className="text-[13px] text-[#5A6A8A] mt-1">Build a fact-safe resume from your student profile, skills, projects, courses and certificates.</p></div>{(error||message)&&<div className={`p-3 rounded-xl text-[12px] ${error?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-700"}`}>{error||message}</div>}
    <div className="p-4 rounded-xl bg-[#EBF1FA] grid sm:grid-cols-3 gap-3 text-[11.5px]"><span><b>Name:</b> {data.auto.full_name}</span><span><b>Email:</b> {data.auto.email}</span><span><b>Skills synced:</b> {data.auto.skills.length}</span></div>
    <div className="grid sm:grid-cols-2 gap-3"><input className={input} value={data.profile.headline||""} placeholder="Professional headline" onChange={e=>profile("headline",e.target.value)}/><input className={input} value={data.profile.location||""} placeholder="Location" onChange={e=>profile("location",e.target.value)}/><input className={input} value={data.profile.linkedin_url||""} placeholder="LinkedIn URL" onChange={e=>profile("linkedin_url",e.target.value)}/><input className={input} value={data.profile.github_url||""} placeholder="GitHub URL" onChange={e=>profile("github_url",e.target.value)}/><input className={input} value={data.profile.portfolio_url||""} placeholder="Portfolio URL" onChange={e=>profile("portfolio_url",e.target.value)}/></div><textarea className={input} rows={4} value={data.profile.professional_summary||""} placeholder="About you (facts only; Groq will polish the wording)" onChange={e=>profile("professional_summary",e.target.value)}/>
    <Entries label="Education" items={data.profile.educations} onChange={x=>profile("educations",x)}/><Entries label="Experience" items={data.profile.experiences} onChange={x=>profile("experiences",x)}/><Entries label="Projects" items={data.profile.projects} onChange={x=>profile("projects",x)}/><Entries label="Certifications" items={data.profile.certifications} onChange={x=>profile("certifications",x)}/>
    <div className="grid sm:grid-cols-2 gap-3"><textarea className={input} rows={3} value={data.profile.achievements.join("\n")} placeholder="Achievements — one per line" onChange={e=>profile("achievements",e.target.value.split("\n").filter(Boolean))}/><textarea className={input} rows={3} value={data.profile.languages.join("\n")} placeholder="Languages — one per line" onChange={e=>profile("languages",e.target.value.split("\n").filter(Boolean))}/></div>
    <div className="flex justify-end"><button onClick={save} disabled={!!busy} className="flex items-center gap-2 px-5 py-2.5 border border-[#1B3A6B] text-[#1B3A6B] rounded-xl text-[12px] font-semibold disabled:opacity-50"><Save size={14}/>{busy==="save"?"Saving…":"Save Information"}</button></div>
    <div className="p-5 rounded-2xl bg-[#1B3A6B] text-white"><div className="flex flex-col sm:flex-row gap-3"><input className="flex-1 px-4 py-3 rounded-xl text-[#0F1C3F] text-[13px]" value={target} placeholder="Target role, e.g. Backend Developer" onChange={e=>setTarget(e.target.value)}/><button disabled={!!busy||target.trim().length<2} onClick={generate} className="flex items-center justify-center gap-2 px-5 py-3 bg-[#D97706] rounded-xl text-[12.5px] font-semibold disabled:opacity-50"><Sparkles size={15}/>{busy==="generate"?"Generating…":"Generate ATS Resume"}</button></div><p className="text-[10.5px] text-white/55 mt-2">AI improves wording only. It will not invent experience, dates or achievements.</p></div>
    {versions.length>0&&<div className="flex gap-2 overflow-x-auto">{versions.map(v=><button key={v.id} onClick={()=>getGeneratedResume(v.id).then(setCurrent)} className={`px-3 py-2 rounded-lg text-[11px] whitespace-nowrap ${current?.id===v.id?"bg-[#1B3A6B] text-white":"bg-[#EFF2FA] text-[#5A6A8A]"}`}>Version {v.version} · {v.target_role}</button>)}</div>}
    {current?.content&&<div className="border border-[#E3E8F2] rounded-2xl overflow-hidden"><div className="p-5 bg-[#F8FAFD] flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div className="flex items-center gap-4"><div className="w-16 h-16 rounded-full border-[6px] border-emerald-500 flex items-center justify-center text-[18px] font-bold text-[#0F1C3F]">{current.ats?.score||0}</div><div><h3 className="font-semibold text-[#0F1C3F]">ATS score · Grade {current.ats?.grade}</h3><p className="text-[11.5px] text-[#5A6A8A]">Version {current.version} · {current.target_role}</p></div></div><button onClick={()=>studentDownload(`/api/v1/students/me/resumes/${current.id}/download`,`resume-v${current.version}.pdf`).catch(e=>setError(e.message))} className="flex items-center justify-center gap-2 px-4 py-2.5 bg-[#1B3A6B] text-white rounded-xl text-[12px] font-semibold"><Download size={14}/>Download PDF</button></div><div className="p-5 space-y-4"><label className="block text-[11px] font-semibold text-[#5A6A8A]">Professional summary<textarea className={`${input} mt-2`} rows={5} value={current.content.professional_summary} onChange={e=>updateContent("professional_summary",e.target.value)}/></label><label className="block text-[11px] font-semibold text-[#5A6A8A]">Skills<input className={`${input} mt-2`} value={current.content.skills.join(", ")} onChange={e=>updateContent("skills",e.target.value.split(",").map(v=>v.trim()).filter(Boolean))}/></label><Entries label="Generated Experience" items={current.content.experiences} onChange={x=>updateContent("experiences",x)}/><Entries label="Generated Projects" items={current.content.projects} onChange={x=>updateContent("projects",x)}/>{current.ats?.issues?.length?<div className="p-4 bg-amber-50 rounded-xl"><p className="text-[12px] font-semibold text-amber-800">How to improve</p>{current.ats.issues.map(x=><p key={x} className="text-[11.5px] text-amber-700 mt-1">• {x}</p>)}</div>:<div className="flex gap-2 text-emerald-700 text-[12px]"><Check size={15}/>No critical ATS issues found.</div>}<button onClick={saveGenerated} disabled={!!busy} className="w-full py-3 bg-[#1B3A6B] text-white rounded-xl text-[12.5px] font-semibold disabled:opacity-50">{busy==="resume"?"Saving…":"Save Edits & Recalculate ATS Score"}</button></div></div>}
  </div>;
}
