import { useEffect, useState } from "react";
import { AlertCircle, CheckCircle2, GraduationCap, ShieldCheck } from "lucide-react";

const API_URL=(import.meta.env.VITE_API_URL||"http://localhost:8000").replace(/\/$/,"");
interface Verification {is_valid:boolean;certificate_number:string;student_name:string;course_title:string;issued_at:string;status:string;revoked_at?:string|null;revocation_reason?:string|null}

export function CertificateVerification({token,onHome}:{token:string;onHome:()=>void}){
  const [data,setData]=useState<Verification|null>(null);const [error,setError]=useState("");
  useEffect(()=>{fetch(`${API_URL}/api/v1/certificates/verify/${encodeURIComponent(token)}`).then(async response=>{const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.detail||"Certificate not found");return body;}).then(setData).catch(e=>setError(e.message));},[token]);
  return <div className="min-h-screen bg-[#F2F5FC] flex flex-col" style={{fontFamily:"var(--font-sans)"}}><header className="bg-[#1B3A6B] text-white"><div className="max-w-5xl mx-auto px-5 py-4 flex items-center justify-between"><div className="flex items-center gap-3"><span className="w-9 h-9 rounded-xl bg-white/10 flex items-center justify-center"><GraduationCap size={18}/></span><div><p className="text-[14px] font-semibold">EduConnect</p><p className="text-[10px] text-white/50">Certificate Verification</p></div></div><button onClick={onHome} className="px-3 py-2 rounded-xl bg-white/10 text-[11px]">Go to Home</button></div></header><main className="flex-1 px-5 py-12 flex items-center justify-center"><div className="w-full max-w-xl bg-white border border-[rgba(27,58,107,0.08)] rounded-3xl shadow-sm overflow-hidden">{!data&&!error?<div className="py-20 text-center text-[13px] text-[#5A6A8A]">Verifying certificate…</div>:error?<div className="p-10 text-center"><span className="w-16 h-16 mx-auto rounded-2xl bg-red-50 flex items-center justify-center"><AlertCircle size={28} className="text-red-600"/></span><h1 className="text-[22px] font-semibold text-[#0F1C3F] mt-5">Certificate not found</h1><p className="text-[13px] text-[#5A6A8A] mt-2">{error}</p></div>:data&&<><div className={`p-6 text-center ${data.is_valid?"bg-emerald-50":"bg-red-50"}`}><span className={`w-14 h-14 mx-auto rounded-2xl flex items-center justify-center ${data.is_valid?"bg-emerald-600 text-white":"bg-red-600 text-white"}`}>{data.is_valid?<CheckCircle2 size={26}/>:<AlertCircle size={26}/>}</span><h1 className={`text-[21px] font-semibold mt-4 ${data.is_valid?"text-emerald-800":"text-red-800"}`}>{data.is_valid?"Valid Certificate":"Certificate Invalid"}</h1><p className="text-[11px] mt-1 opacity-70">Verified directly by EduConnect</p></div><div className="p-7 space-y-4"><div><p className="text-[10px] uppercase tracking-wider text-[#9AA5BE]">Awarded to</p><p className="text-[18px] font-semibold text-[#0F1C3F] mt-1">{data.student_name}</p></div><div><p className="text-[10px] uppercase tracking-wider text-[#9AA5BE]">Course</p><p className="text-[15px] font-medium text-[#0F1C3F] mt-1">{data.course_title}</p></div><div className="grid grid-cols-2 gap-4 pt-4 border-t"><div><p className="text-[10px] text-[#9AA5BE]">Certificate number</p><p className="text-[11.5px] font-semibold mt-1">{data.certificate_number}</p></div><div><p className="text-[10px] text-[#9AA5BE]">Issued on</p><p className="text-[11.5px] font-semibold mt-1">{new Date(data.issued_at).toLocaleDateString()}</p></div></div>{!data.is_valid&&<div className="p-3 bg-red-50 text-red-700 rounded-xl text-[11.5px]">{data.revocation_reason||"This certificate has been revoked or superseded."}</div>}</div></>}</div></main><footer className="pb-8 text-center text-[10.5px] text-[#9AA5BE] flex items-center justify-center gap-1.5"><ShieldCheck size={12}/>Secure public verification</footer></div>;
}
