import { useState } from "react";
import { ArrowRight, Award, BookOpen, Building2, CheckCircle2, FileCheck2, GraduationCap, LayoutDashboard, LogIn, Menu, Route, ShieldCheck, Sparkles, Users, X } from "lucide-react";

type HomeProps = { onCollege: () => void; onStudentLogin: () => void; onAdminLogin: () => void; onStudentRegister: () => void };
const capabilities = [
  { icon: Building2, title: "Institution operations", desc: "Review institutions, manage college profiles and keep every college securely scoped." },
  { icon: Users, title: "Student management", desc: "Organize students, programs, batches, sections, faculty and course allocations." },
  { icon: Route, title: "AI career roadmap", desc: "Turn a student's skills and career goal into an actionable learning roadmap." },
  { icon: BookOpen, title: "Structured learning", desc: "Deliver courses with video, article, quiz, assignment and coding-test lessons." },
  { icon: FileCheck2, title: "ATS resume studio", desc: "Import profile data, build resume versions and review ATS readiness." },
  { icon: Award, title: "Progress & certificates", desc: "Track activity, evaluations, completion and verifiable certificates." },
];
const journeys = [
  { icon: GraduationCap, label: "Student", title: "Plan your career and keep learning", points: ["Build skills and career profile", "Generate a personalized roadmap", "Learn, submit and earn certificates"], action: "Student sign in" },
  { icon: Building2, label: "College Admin", title: "Run college learning operations", points: ["Manage students and academic groups", "Allocate courses by program", "Monitor progress and reports"], action: "College admin sign in" },
  { icon: ShieldCheck, label: "LMS Admin", title: "Manage the platform centrally", points: ["Review institution requests", "Publish courses and assessments", "Oversee evaluations and certificates"], action: "LMS admin sign in" },
] as const;

export function HomePage({ onCollege, onStudentLogin, onAdminLogin, onStudentRegister }: HomeProps) {
  const [mobileOpen, setMobileOpen] = useState(false);
  return <div className="min-h-screen bg-white text-[#0F1C3F]" style={{ fontFamily: "var(--font-sans)" }}>
    <nav className="sticky top-0 z-50 border-b border-slate-200/80 bg-white/95 backdrop-blur">
      <div className="mx-auto flex max-w-[1180px] items-center justify-between px-4 py-3.5 sm:px-6">
        <button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} className="flex items-center gap-2.5" aria-label="EduConnect home"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#1B3A6B] text-white"><GraduationCap size={18}/></span><span className="text-[17px] font-bold">EduConnect</span></button>
        <div className="hidden items-center gap-7 text-[14px] font-medium text-[#5A6A8A] md:flex"><a href="#product" className="hover:text-[#1B3A6B]">Product</a><a href="#workspaces" className="hover:text-[#1B3A6B]">Workspaces</a><a href="#workflow" className="hover:text-[#1B3A6B]">How it works</a></div>
        <div className="hidden items-center gap-2 md:flex"><button onClick={onAdminLogin} className="rounded-xl px-4 py-2.5 text-[13.5px] font-semibold text-[#1B3A6B] hover:bg-[#EBF1FA]"><LogIn size={14} className="mr-2 inline"/>Sign in</button><button onClick={onCollege} className="rounded-xl bg-[#1B3A6B] px-4 py-2.5 text-[13.5px] font-semibold text-white hover:bg-[#122748]">Register institution</button></div>
        <button onClick={() => setMobileOpen(v => !v)} className="rounded-lg p-2 md:hidden" aria-label="Toggle navigation">{mobileOpen ? <X size={20}/> : <Menu size={20}/>}</button>
      </div>
      {mobileOpen && <div className="border-t border-slate-100 px-4 py-4 md:hidden"><div className="space-y-1 text-[14px] font-medium text-[#5A6A8A]">{[['Product','#product'],['Workspaces','#workspaces'],['How it works','#workflow']].map(([label,href])=><a key={label} href={href} onClick={()=>setMobileOpen(false)} className="block rounded-lg px-3 py-2.5 hover:bg-slate-50">{label}</a>)}</div><div className="mt-3 grid gap-2"><button onClick={onAdminLogin} className="rounded-xl border border-slate-200 py-2.5 text-[14px] font-semibold">Sign in</button><button onClick={onCollege} className="rounded-xl bg-[#1B3A6B] py-2.5 text-[14px] font-semibold text-white">Register institution</button></div></div>}
    </nav>
    <main>
      <section className="relative overflow-hidden bg-[#09172B]"><div className="absolute inset-0 opacity-[0.05]" style={{backgroundImage:"linear-gradient(#fff 1px,transparent 1px),linear-gradient(90deg,#fff 1px,transparent 1px)",backgroundSize:"44px 44px"}}/><div className="relative mx-auto grid max-w-[1180px] items-center gap-12 px-4 py-20 sm:px-6 sm:py-28 lg:grid-cols-[1.1fr_.9fr]"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3.5 py-1.5 text-[12px] font-medium text-white/80"><Sparkles size={13} className="text-amber-400"/>College learning and career readiness</div><h1 className="max-w-3xl text-[42px] font-bold leading-[1.08] text-white sm:text-[58px]" style={{fontFamily:"var(--font-serif)"}}>One clear path from student profile to course completion.</h1><p className="mt-6 max-w-2xl text-[16px] leading-7 text-white/65">EduConnect brings institution operations, AI-assisted career planning and structured LMS delivery into one role-based platform.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><button onClick={onStudentRegister} className="flex items-center justify-center gap-2 rounded-xl bg-amber-500 px-6 py-3.5 text-[14px] font-bold text-[#09172B] hover:bg-amber-400">Create student account <ArrowRight size={16}/></button><button onClick={onStudentLogin} className="flex items-center justify-center gap-2 rounded-xl border border-white/20 bg-white/10 px-6 py-3.5 text-[14px] font-semibold text-white hover:bg-white/15"><LogIn size={15}/>Student sign in</button></div></div><div className="rounded-3xl border border-white/10 bg-white/[0.07] p-5 shadow-2xl backdrop-blur sm:p-7"><p className="text-[12px] font-semibold uppercase tracking-[.18em] text-white/45">A connected student journey</p><div className="mt-5 space-y-3">{["Build career profile","Generate roadmap","Enroll and learn","Complete assessments","Earn certificate"].map((item,index)=><div key={item} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.06] p-3.5"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-xl bg-white/10 text-[12px] font-bold text-amber-300">{index+1}</span><span className="text-[14px] font-medium text-white/85">{item}</span></div>)}</div></div></div></section>
      <section id="product" className="bg-[#F4F6FB]"><div className="mx-auto max-w-[1180px] px-4 py-16 sm:px-6 sm:py-20"><div className="max-w-2xl"><p className="text-[12px] font-bold uppercase tracking-[.18em] text-[#1B3A6B]">What is available today</p><h2 className="mt-3 text-[32px] font-bold sm:text-[40px]" style={{fontFamily:"var(--font-serif)"}}>Real workflows, connected end to end</h2><p className="mt-3 text-[15px] leading-6 text-[#5A6A8A]">The platform focuses on the operations students and institutions use every day.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{capabilities.map(item=><article key={item.title} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#EBF1FA] text-[#1B3A6B]"><item.icon size={19}/></span><h3 className="mt-4 text-[16px] font-bold">{item.title}</h3><p className="mt-2 text-[14px] leading-6 text-[#5A6A8A]">{item.desc}</p></article>)}</div></div></section>
      <section id="workspaces"><div className="mx-auto max-w-[1180px] px-4 py-16 sm:px-6 sm:py-20"><div className="text-center"><p className="text-[12px] font-bold uppercase tracking-[.18em] text-amber-700">Role-based workspaces</p><h2 className="mt-3 text-[32px] font-bold sm:text-[40px]" style={{fontFamily:"var(--font-serif)"}}>Start in the workspace built for your role</h2></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{journeys.map((item,index)=><article key={item.label} className="flex flex-col rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#EBF1FA] text-[#1B3A6B]"><item.icon size={20}/></span><p className="mt-4 text-[12px] font-bold uppercase tracking-wider text-[#5A6A8A]">{item.label}</p><h3 className="mt-2 text-[20px] font-bold">{item.title}</h3><ul className="my-6 space-y-3">{item.points.map(point=><li key={point} className="flex gap-2.5 text-[14px] text-[#5A6A8A]"><CheckCircle2 size={16} className="mt-0.5 shrink-0 text-emerald-600"/>{point}</li>)}</ul><button onClick={index===0?onStudentLogin:onAdminLogin} className="mt-auto flex items-center justify-center gap-2 rounded-xl border border-[#1B3A6B]/20 px-4 py-3 text-[13.5px] font-bold text-[#1B3A6B] hover:bg-[#EBF1FA]">{item.action}<ArrowRight size={14}/></button></article>)}</div></div></section>
      <section id="workflow" className="bg-[#1B3A6B] py-16 text-white"><div className="mx-auto flex max-w-[1180px] flex-col items-start justify-between gap-7 px-4 sm:px-6 lg:flex-row lg:items-center"><div><p className="text-[12px] font-bold uppercase tracking-[.18em] text-white/50">For institutions</p><h2 className="mt-2 text-[30px] font-bold" style={{fontFamily:"var(--font-serif)"}}>Bring your college onto one managed platform.</h2><p className="mt-2 max-w-2xl text-[14px] leading-6 text-white/65">Submit institution details for LMS Admin review. Once approved, your College Admin can configure programs, students, faculty and learning access.</p></div><button onClick={onCollege} className="shrink-0 rounded-xl bg-white px-6 py-3.5 text-[14px] font-bold text-[#1B3A6B] hover:bg-slate-100">Register institution</button></div></section>
    </main>
    <footer className="bg-[#06101E] py-8"><div className="mx-auto flex max-w-[1180px] flex-col items-center justify-between gap-4 px-4 text-center sm:px-6 md:flex-row md:text-left"><div className="flex items-center gap-2 text-white"><LayoutDashboard size={16}/><span className="text-[14px] font-bold">EduConnect</span></div><p className="text-[12.5px] text-white/45">Role-based learning and career operations for colleges.</p><p className="text-[12px] text-white/35">© {new Date().getFullYear()} EduConnect</p></div></footer>
  </div>;
}
