import { useEffect, useState } from "react";
import { Award, BookOpen, Brain, Check, ChevronRight, Clock, FileText, GraduationCap, LogOut, Plus, RefreshCw, Route, Sparkles, Target, Trash2, Upload, UserRound, Wrench } from "lucide-react";
import { getCurrentStudent } from "../api/student-auth";
import type { CurrentStudent } from "../api/student-auth";
import { enrollCourse, generateRoadmap, loadEnrolledCourse, loadEnrollments, loadGoal, loadResume, loadRoadmap, loadSkills, loadStudentQuiz, saveGoal, saveLessonProgress, saveSkills, startQuizAttempt, submitQuizAttempt, uploadResume } from "../api/student-career";
import type { CareerGoal, Enrollment, EnrolledCourse, ResumeInfo, Roadmap, StudentSkill } from "../api/student-career";
import { CoursePlayer } from "./course-player";
import type { CourseData } from "./course-player";
import type { Lesson } from "./course-player";

type Section = "skills" | "goal" | "resume" | "roadmap" | "courses";
const NAV = [
  { key: "skills" as const, label: "My Skills", desc: "What you know today", icon: Wrench },
  { key: "goal" as const, label: "Career Goal", desc: "Where you want to go", icon: Target },
  { key: "resume" as const, label: "Resume", desc: "Optional career context", icon: FileText },
  { key: "roadmap" as const, label: "My Roadmap", desc: "AI learning path", icon: Route },
  { key: "courses" as const, label: "My Courses", desc: "Your enrollments", icon: BookOpen },
];
const field = "w-full px-3.5 py-2.5 bg-[#EFF2FA] border-[1.5px] border-transparent rounded-[10px] text-[13px] text-[#0F1C3F] outline-none focus:border-[#1B3A6B] focus:bg-white transition-all";

function LiveQuiz({lesson,onPassed}:{lesson:Lesson;onPassed:()=>void}){
  const [quiz,setQuiz]=useState<Awaited<ReturnType<typeof loadStudentQuiz>>|null>(null);const [answers,setAnswers]=useState<Record<string,string[]>>({});const [attemptId,setAttemptId]=useState("");const [result,setResult]=useState<{percentage:number;passed:boolean;earned_marks:number;total_marks:number}|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  useEffect(()=>{loadStudentQuiz(lesson.id).then(setQuiz).catch(e=>setError(e.message));},[lesson.id]);
  const start=async()=>{if(!quiz)return;setBusy(true);setError("");try{const attempt=await startQuizAttempt(quiz.id);setAttemptId(attempt.id);}catch(e){setError(e instanceof Error?e.message:"Unable to start quiz");}finally{setBusy(false);}};
  const choose=(qid:string,oid:string,multiple:boolean)=>setAnswers(current=>{const selected=current[qid]||[];return {...current,[qid]:multiple?(selected.includes(oid)?selected.filter(x=>x!==oid):[...selected,oid]):[oid]};});
  const submit=async()=>{if(!attemptId)return;setBusy(true);setError("");try{const value=await submitQuizAttempt(attemptId,Object.entries(answers).map(([question_id,selected_option_ids])=>({question_id,selected_option_ids})));setResult(value);if(value.passed)onPassed();}catch(e){setError(e instanceof Error?e.message:"Unable to submit quiz");}finally{setBusy(false);}};
  if(error&&!quiz)return <Notice error={error}/>;if(!quiz)return <div className="p-8 text-center text-[13px] text-[#5A6A8A]">Loading quiz…</div>;
  if(result)return <div className={`p-8 rounded-2xl text-center border ${result.passed?"bg-emerald-50 border-emerald-200":"bg-red-50 border-red-200"}`}><Award size={34} className={`mx-auto ${result.passed?"text-emerald-600":"text-red-500"}`}/><h3 className="text-[20px] font-bold mt-3">{result.passed?"Quiz passed!":"Keep learning and try again"}</h3><p className="text-[13px] mt-2">Score: {result.earned_marks}/{result.total_marks} · {result.percentage}%</p></div>;
  if(!attemptId)return <div className="p-6 bg-white rounded-2xl border border-slate-200"><h3 className="text-[17px] font-semibold">Quiz instructions</h3><p className="text-[13px] text-[#5A6A8A] mt-2">{quiz.instructions}</p><div className="flex gap-4 mt-4 text-[12px] text-[#5A6A8A]"><span>{quiz.questions.length} questions</span><span>Pass: {quiz.passing_percentage}%</span><span>{quiz.remaining_attempts} attempts left</span></div><button disabled={busy||quiz.remaining_attempts===0} onClick={start} className="mt-5 px-5 py-2.5 bg-[#1B3A6B] text-white rounded-xl text-[13px] font-semibold disabled:opacity-40">Start Quiz</button></div>;
  return <div className="space-y-4"><Notice error={error}/>{quiz.questions.map((q,index)=><div key={q.id} className="p-5 bg-white rounded-2xl border border-slate-200"><p className="text-[13px] font-semibold">{index+1}. {q.question_text} <span className="text-[#9AA5BE]">({q.marks} marks)</span></p><div className="space-y-2 mt-3">{q.options.map(o=><label key={o.id} className={`flex gap-3 p-3 rounded-xl border cursor-pointer ${(answers[q.id]||[]).includes(o.id)?"border-[#1B3A6B] bg-[#EBF1FA]":"border-slate-200"}`}><input type={q.question_type==="multiple_choice"?"checkbox":"radio"} name={q.id} checked={(answers[q.id]||[]).includes(o.id)} onChange={()=>choose(q.id,o.id,q.question_type==="multiple_choice")}/><span className="text-[12.5px]">{o.option_text}</span></label>)}</div></div>)}<button disabled={busy} onClick={submit} className="w-full py-3 bg-[#1B3A6B] text-white rounded-xl text-[13.5px] font-semibold disabled:opacity-50">{busy?"Submitting…":"Submit Quiz"}</button></div>;
}

function Notice({ error, success }: { error?: string; success?: string }) {
  if (!error && !success) return null;
  return <div className={`px-4 py-3 rounded-xl text-[12.5px] ${error ? "bg-red-50 text-red-700 border border-red-100" : "bg-emerald-50 text-emerald-700 border border-emerald-100"}`}>{error || success}</div>;
}

function SkillsView({ onReady }: { onReady: () => void }) {
  const [items, setItems] = useState<StudentSkill[]>([]);
  const [draft, setDraft] = useState<StudentSkill>({ name: "", category: "Frontend", proficiency_level: "Beginner", experience_months: 0 });
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { loadSkills().then(setItems).catch(e => setError(e.message)); }, []);
  const add = () => { if (!draft.name.trim()) return; setItems(x => [...x, { ...draft, name: draft.name.trim() }]); setDraft({ name: "", category: "Frontend", proficiency_level: "Beginner", experience_months: 0 }); };
  const save = async () => { setSaving(true); setError(""); try { const result = await saveSkills(items); setItems(result); setMessage("Skills saved successfully."); onReady(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save skills"); } finally { setSaving(false); } };
  return <div className="space-y-5">
    <div><h2 className="text-[21px] text-[#0F1C3F]" style={{fontFamily:"var(--font-serif)"}}>What skills do you have?</h2><p className="text-[13px] text-[#5A6A8A] mt-1">Add your current skills honestly. Your roadmap will start from this foundation.</p></div>
    <Notice error={error} success={message}/>
    <div className="grid grid-cols-[1.4fr_1fr_1fr_0.8fr_auto] gap-3 p-4 bg-[#F4F7FC] rounded-2xl border border-[--border]">
      <input className={field} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="Skill, e.g. JavaScript" />
      <select className={field} value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{["Frontend","Backend","Programming Language","Database","DevOps","AI/ML","Design","Soft Skill","Other"].map(x=><option key={x}>{x}</option>)}</select>
      <select className={field} value={draft.proficiency_level} onChange={e=>setDraft({...draft,proficiency_level:e.target.value as StudentSkill["proficiency_level"]})}>{["Beginner","Intermediate","Advanced","Expert"].map(x=><option key={x}>{x}</option>)}</select>
      <input className={field} type="number" min={0} max={600} value={draft.experience_months ?? 0} onChange={e=>setDraft({...draft,experience_months:Number(e.target.value)})} placeholder="Months" />
      <button onClick={add} className="px-4 bg-[#1B3A6B] text-white rounded-[10px] hover:bg-[#122748]"><Plus size={16}/></button>
    </div>
    <div className="space-y-2">{items.map((s,i)=><div key={`${s.name}-${i}`} className="flex items-center gap-4 p-4 bg-white border border-[--border] rounded-xl">
      <div className="w-9 h-9 rounded-lg bg-[#EBF1FA] flex items-center justify-center"><Wrench size={15} className="text-[#1B3A6B]"/></div><div className="flex-1"><p className="text-[13.5px] font-semibold text-[#0F1C3F]">{s.name}</p><p className="text-[11.5px] text-[#5A6A8A]">{s.category} · {s.proficiency_level}{s.experience_months ? ` · ${s.experience_months} months` : ""}</p></div><button onClick={()=>setItems(x=>x.filter((_,n)=>n!==i))} className="p-2 text-[#9AA5BE] hover:text-red-500"><Trash2 size={14}/></button>
    </div>)}</div>
    {items.length===0&&<div className="py-10 text-center text-[13px] text-[#9AA5BE] border-2 border-dashed border-slate-200 rounded-2xl">No skills added yet.</div>}
    <div className="flex justify-end"><button disabled={saving||!items.length} onClick={save} className="px-5 py-2.5 bg-[#1B3A6B] text-white rounded-[10px] text-[13px] font-semibold disabled:opacity-50">{saving?"Saving…":"Save Skills"}</button></div>
  </div>;
}

function GoalView({ onReady }: { onReady: () => void }) {
  const [goal,setGoal]=useState<CareerGoal>({target_role:"",preferred_domain:"",current_level:"Beginner",target_duration_months:6,weekly_learning_hours:10,goal_description:""});
  const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState("");
  useEffect(()=>{loadGoal().then(x=>x&&setGoal(x)).catch(e=>setError(e.message));},[]);
  const save=async()=>{setSaving(true);setError("");try{setGoal(await saveGoal(goal));setSuccess("Career goal saved successfully.");onReady();}catch(e){setError(e instanceof Error?e.message:"Unable to save goal");}finally{setSaving(false);}};
  return <div className="space-y-6"><div><h2 className="text-[21px] text-[#0F1C3F]" style={{fontFamily:"var(--font-serif)"}}>Define your career goal</h2><p className="text-[13px] text-[#5A6A8A] mt-1">Tell us the role you want and the time you can invest.</p></div><Notice error={error} success={success}/>
    <div className="grid grid-cols-2 gap-5">
      <label className="space-y-1.5"><span className="text-[13px] font-medium">Target Role *</span><input className={field} value={goal.target_role} onChange={e=>setGoal({...goal,target_role:e.target.value})} placeholder="Full Stack Developer"/></label>
      <label className="space-y-1.5"><span className="text-[13px] font-medium">Preferred Domain *</span><input className={field} value={goal.preferred_domain} onChange={e=>setGoal({...goal,preferred_domain:e.target.value})} placeholder="Web Development"/></label>
      <label className="space-y-1.5"><span className="text-[13px] font-medium">Current Level</span><select className={field} value={goal.current_level} onChange={e=>setGoal({...goal,current_level:e.target.value as CareerGoal["current_level"]})}>{["Beginner","Intermediate","Advanced"].map(x=><option key={x}>{x}</option>)}</select></label>
      <label className="space-y-1.5"><span className="text-[13px] font-medium">Roadmap Duration</span><select className={field} value={goal.target_duration_months} onChange={e=>setGoal({...goal,target_duration_months:Number(e.target.value)})}>{[3,6,9,12].map(x=><option key={x} value={x}>{x} months</option>)}</select></label>
      <label className="space-y-1.5"><span className="text-[13px] font-medium">Weekly Learning Hours</span><input className={field} type="number" min={1} max={60} value={goal.weekly_learning_hours} onChange={e=>setGoal({...goal,weekly_learning_hours:Number(e.target.value)})}/></label>
      <label className="space-y-1.5 col-span-2"><span className="text-[13px] font-medium">Goal Description <span className="text-[#9AA5BE]">(optional)</span></span><textarea className={`${field} resize-none`} rows={4} value={goal.goal_description||""} onChange={e=>setGoal({...goal,goal_description:e.target.value})} placeholder="What kind of work do you want to be ready for?"/></label>
    </div><div className="flex justify-end"><button disabled={saving||!goal.target_role||!goal.preferred_domain} onClick={save} className="px-5 py-2.5 bg-[#1B3A6B] text-white rounded-[10px] text-[13px] font-semibold disabled:opacity-50">{saving?"Saving…":"Save Career Goal"}</button></div>
  </div>;
}

function ResumeView({ onReady }: { onReady: () => void }) {
  const [resume,setResume]=useState<ResumeInfo|null>(null);const [uploading,setUploading]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{loadResume().then(setResume).catch(e=>setError(e.message));},[]);
  const upload=async(file?:File)=>{if(!file)return;setUploading(true);setError("");try{const result=await uploadResume(file);setResume(result);onReady();}catch(e){setError(e instanceof Error?e.message:"Upload failed");}finally{setUploading(false);}};
  return <div className="space-y-6"><div><h2 className="text-[21px] text-[#0F1C3F]" style={{fontFamily:"var(--font-serif)"}}>Add your resume</h2><p className="text-[13px] text-[#5A6A8A] mt-1">Optional. It gives the roadmap more context about your projects and experience.</p></div><Notice error={error}/>
    <label className="flex flex-col items-center gap-3 py-12 border-2 border-dashed border-[#1B3A6B]/25 bg-[#F8FAFD] rounded-2xl cursor-pointer hover:bg-[#EBF1FA]/50 transition-colors"><div className="w-12 h-12 rounded-xl bg-[#EBF1FA] flex items-center justify-center">{uploading?<RefreshCw size={20} className="animate-spin text-[#1B3A6B]"/>:<Upload size={20} className="text-[#1B3A6B]"/>}</div><div className="text-center"><p className="text-[13.5px] font-semibold text-[#1B3A6B]">{uploading?"Processing resume…":"Choose PDF or DOCX"}</p><p className="text-[11.5px] text-[#9AA5BE] mt-1">Maximum 5 MB</p></div><input type="file" accept=".pdf,.docx" className="hidden" disabled={uploading} onChange={e=>upload(e.target.files?.[0])}/></label>
    {resume&&<div className="p-5 border border-emerald-200 bg-emerald-50 rounded-2xl flex gap-4"><div className="w-10 h-10 rounded-xl bg-white flex items-center justify-center"><FileText size={18} className="text-emerald-600"/></div><div className="flex-1"><p className="text-[13.5px] font-semibold text-[#0F1C3F]">{resume.file_name}</p><p className="text-[11.5px] text-emerald-700 mt-0.5">{resume.parsing_status==="processed"?"Resume processed successfully":resume.parsing_status}</p>{resume.parsed_data.detected_skills?.length?<div className="flex flex-wrap gap-1.5 mt-3">{resume.parsed_data.detected_skills.map(x=><span key={x} className="px-2 py-1 rounded-full bg-white text-[10.5px] text-[#1B3A6B]">{x}</span>)}</div>:null}</div><Check size={18} className="text-emerald-600"/></div>}
  </div>;
}

function RoadmapView({ readiness, onEnroll }: { readiness:{skills:boolean;goal:boolean}; onEnroll:()=>void }) {
  const [roadmap,setRoadmap]=useState<Roadmap|null>(null);const [generating,setGenerating]=useState(false);const [error,setError]=useState("");const [enrolled,setEnrolled]=useState<Set<string>>(new Set());
  useEffect(()=>{loadRoadmap().then(value=>{setRoadmap(value);setEnrolled(new Set(value?.recommendations.filter(x=>x.is_enrolled).map(x=>x.course_id)||[]));}).catch(e=>setError(e.message));},[]);
  const generate=async()=>{setGenerating(true);setError("");try{setRoadmap(await generateRoadmap());}catch(e){setError(e instanceof Error?e.message:"Generation failed");}finally{setGenerating(false);}};
  const enroll=async(id:string)=>{if(!roadmap)return;setError("");try{await enrollCourse(id,roadmap.id);setEnrolled(x=>new Set(x).add(id));onEnroll();}catch(e){setError(e instanceof Error?e.message:"Enrollment failed");}};
  if(!roadmap)return <div className="space-y-6"><div><h2 className="text-[21px] text-[#0F1C3F]" style={{fontFamily:"var(--font-serif)"}}>Generate your learning roadmap</h2><p className="text-[13px] text-[#5A6A8A] mt-1">Groq will create a structured path from your skills, goal and optional resume.</p></div><Notice error={error}/><div className="py-14 flex flex-col items-center text-center bg-gradient-to-br from-[#F4F7FC] to-[#EBF1FA] rounded-2xl border border-[--border]"><div className="w-16 h-16 rounded-2xl bg-[#1B3A6B] flex items-center justify-center shadow-lg"><Brain size={28} className="text-white"/></div><h3 className="mt-5 text-[18px] font-semibold text-[#0F1C3F]">Your personalized path is ready to be planned</h3><div className="flex gap-4 mt-4 text-[12px]"><span className={readiness.skills?"text-emerald-600":"text-red-500"}>{readiness.skills?"✓":"○"} Skills added</span><span className={readiness.goal?"text-emerald-600":"text-red-500"}>{readiness.goal?"✓":"○"} Goal defined</span><span className="text-[#5A6A8A]">Resume optional</span></div><button onClick={generate} disabled={generating||!readiness.skills||!readiness.goal} className="mt-7 flex items-center gap-2 px-6 py-3 bg-[#D97706] text-white rounded-xl text-[13.5px] font-semibold disabled:opacity-40">{generating?<RefreshCw size={16} className="animate-spin"/>:<Sparkles size={16}/>} {generating?"Generating roadmap…":"Generate My Roadmap"}</button></div></div>;
  return <div className="space-y-7"><Notice error={error}/><div className="p-6 rounded-2xl bg-[#1B3A6B] text-white"><div className="flex justify-between gap-4"><div><p className="text-[10px] uppercase tracking-widest text-white/50">AI Career Roadmap · Version {roadmap.version}</p><h2 className="text-[22px] mt-2" style={{fontFamily:"var(--font-serif)"}}>{roadmap.title}</h2><p className="text-[12.5px] text-white/65 mt-2 max-w-2xl">{roadmap.summary}</p></div><div className="shrink-0 flex items-center gap-2 text-[12px] bg-white/10 px-3 py-2 rounded-xl h-fit"><Clock size={14}/>{roadmap.duration_weeks} weeks</div></div></div>
    <div><h3 className="text-[14px] font-semibold text-[#0F1C3F] mb-3">Priority skill gaps</h3><div className="grid grid-cols-3 gap-3">{roadmap.skill_gaps.map(g=><div key={g.skill} className="p-4 border border-[--border] rounded-xl"><span className={`text-[10px] uppercase font-bold ${g.priority==="high"?"text-red-500":"text-amber-600"}`}>{g.priority}</span><p className="text-[13.5px] font-semibold mt-1">{g.skill}</p><p className="text-[11.5px] text-[#5A6A8A] mt-1">{g.reason}</p></div>)}</div></div>
    <div className="space-y-4">{roadmap.phases.map(p=><div key={p.sequence} className="p-5 border border-[--border] rounded-2xl"><div className="flex gap-4"><div className="w-9 h-9 rounded-xl bg-[#1B3A6B] text-white flex items-center justify-center text-[12px] font-bold">{p.sequence}</div><div className="flex-1"><div className="flex justify-between"><h3 className="text-[15px] font-semibold">{p.title}</h3><span className="text-[11.5px] text-[#5A6A8A]">{p.duration_weeks} weeks</span></div><p className="text-[12px] text-[#5A6A8A] mt-1">{p.objective}</p><div className="flex flex-wrap gap-1.5 mt-3">{p.skills.map(x=><span key={x} className="px-2.5 py-1 bg-[#EBF1FA] text-[#1B3A6B] rounded-full text-[10.5px]">{x}</span>)}</div><ul className="mt-3 space-y-1">{p.milestones.map(x=><li key={x} className="text-[11.5px] text-[#5A6A8A] flex gap-2"><Check size={11} className="text-emerald-600 mt-0.5"/>{x}</li>)}</ul></div></div></div>)}</div>
    <div><h3 className="text-[16px] text-[#0F1C3F] mb-3" style={{fontFamily:"var(--font-serif)"}}>Recommended courses</h3><div className="grid grid-cols-2 gap-4">{roadmap.recommendations.map(c=><div key={c.course_id} className="p-5 border border-[--border] rounded-2xl bg-white"><div className="flex justify-between"><div className="w-10 h-10 rounded-xl bg-[#EBF1FA] flex items-center justify-center"><BookOpen size={17} className="text-[#1B3A6B]"/></div><span className="text-[11px] font-bold text-emerald-600">{c.match_score}% match</span></div><h4 className="text-[14px] font-semibold mt-3">{c.title}</h4><p className="text-[11.5px] text-[#5A6A8A] mt-1 line-clamp-2">{c.reason}</p><div className="flex items-center gap-3 mt-3 text-[10.5px] text-[#9AA5BE]"><span>{c.level}</span><span>{c.duration_hours}h</span></div><button disabled={enrolled.has(c.course_id)} onClick={()=>enroll(c.course_id)} className="w-full mt-4 py-2.5 bg-[#1B3A6B] text-white rounded-[10px] text-[12.5px] font-semibold disabled:bg-emerald-500">{enrolled.has(c.course_id)?"Enrolled ✓":"Enroll in Course"}</button></div>)}</div></div>
  </div>;
}

function CoursesView({ refresh, onOpen }: { refresh:number; onOpen:(courseId:string)=>void }) { const [items,setItems]=useState<Enrollment[]>([]);useEffect(()=>{loadEnrollments().then(setItems).catch(()=>setItems([]));},[refresh]);return <div className="space-y-5"><div><h2 className="text-[21px] text-[#0F1C3F]" style={{fontFamily:"var(--font-serif)"}}>My enrolled courses</h2><p className="text-[13px] text-[#5A6A8A] mt-1">Continue learning and track every completed lesson.</p></div>{items.length?<div className="grid grid-cols-2 gap-4">{items.map(c=><div key={c.id} className="p-5 border border-[--border] rounded-2xl"><div className="flex gap-3"><div className="w-10 h-10 rounded-xl bg-[#EBF1FA] flex items-center justify-center"><GraduationCap size={18} className="text-[#1B3A6B]"/></div><div><h3 className="text-[14px] font-semibold">{c.title}</h3><p className="text-[11.5px] text-[#5A6A8A]">{c.level} · {c.completed_lessons}/{c.lesson_count} lessons</p></div></div><div className="mt-5 flex justify-between text-[11px]"><span className="text-[#5A6A8A]">Progress</span><span className="font-semibold text-[#1B3A6B]">{c.progress_percentage}%</span></div><div className="h-1.5 bg-[#E8ECF5] rounded-full mt-2"><div className="h-full bg-[#1B3A6B] rounded-full" style={{width:`${c.progress_percentage}%`}}/></div><button onClick={()=>onOpen(c.course_id)} disabled={!c.lesson_count} className="w-full mt-4 py-2.5 rounded-[10px] bg-[#1B3A6B] text-white text-[12.5px] font-semibold disabled:opacity-40">{c.progress_percentage?"Continue Learning":"Start Course"}</button></div>)}</div>:<div className="py-14 text-center border-2 border-dashed border-slate-200 rounded-2xl"><BookOpen size={28} className="mx-auto text-[#9AA5BE]"/><p className="mt-3 text-[13px] text-[#5A6A8A]">No courses enrolled yet. Generate your roadmap to see recommendations.</p></div>}</div>; }

export function StudentCareerPortal({ onLogout }: { onLogout:()=>void }) {
  const [section,setSection]=useState<Section>("skills");const [student,setStudent]=useState<CurrentStudent|null>(null);const [ready,setReady]=useState({skills:false,goal:false,resume:false});const [courseRefresh,setCourseRefresh]=useState(0);const [playing,setPlaying]=useState<EnrolledCourse|null>(null);
  useEffect(()=>{getCurrentStudent().then(setStudent);Promise.all([loadSkills(),loadGoal(),loadResume()]).then(([s,g,r])=>setReady({skills:s.length>0,goal:Boolean(g),resume:Boolean(r)}));},[]);
  const active=NAV.find(x=>x.key===section)!;
  if(playing){const course:CourseData={id:playing.id,title:playing.title,instructor:"EduConnect Learning Team",color:"#1B3A6B",emoji:"🎓",totalHours:String(playing.duration_hours),rating:4.8,enrolled:1,description:playing.description,skills:playing.skills,progress:playing.progress_percentage,sections:playing.sections.map(section=>({id:section.id,title:section.title,lessons:section.lessons.map(lesson=>({id:lesson.id,title:lesson.title,type:lesson.lesson_type,duration:String(lesson.duration_minutes),completed:lesson.status==="completed",isPreview:lesson.is_preview,youtubeId:lesson.youtube_id||undefined}))}))};return <CoursePlayer course={course} onBack={()=>{setPlaying(null);setCourseRefresh(x=>x+1);}} onLessonComplete={async lessonId=>{await saveLessonProgress(playing.enrollment_id,lessonId,"completed");}} renderQuiz={(lesson,onPassed)=><LiveQuiz lesson={lesson} onPassed={onPassed}/>}/>;}
  return <div className="min-h-screen bg-[#F2F5FC]" style={{fontFamily:"var(--font-sans)"}}><header className="bg-[#1B3A6B] border-b border-white/10 sticky top-0 z-50"><div className="max-w-[1200px] mx-auto px-7 py-3.5 flex items-center justify-between"><div className="flex items-center gap-3"><div className="w-8 h-8 rounded-[9px] bg-white/10 flex items-center justify-center"><GraduationCap size={17} className="text-white"/></div><div><p className="text-white font-semibold text-[14px] leading-none">EduConnect</p><p className="text-white/45 text-[10.5px] mt-0.5">Student Career Portal</p></div></div><div className="flex items-center gap-4"><div className="hidden md:flex items-center gap-2 text-white/70"><UserRound size={14}/><span className="text-[12px]">{student?.full_name||"Student"}</span></div><button onClick={onLogout} className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-white/10 hover:bg-white/20 text-white/80 text-[11.5px]"><LogOut size={13}/> Logout</button></div></div></header>
    <div className="max-w-[1200px] mx-auto px-7 py-7 grid gap-5" style={{gridTemplateColumns:"252px 1fr"}}><aside className="sticky top-[76px] self-start"><div className="bg-white rounded-2xl border border-[--border] overflow-hidden shadow-sm"><div className="p-5 bg-[#1B3A6B]"><p className="text-[10px] uppercase tracking-widest text-white/50">Career setup</p><p className="text-white text-[13px] font-semibold mt-2">{[ready.skills,ready.goal].filter(Boolean).length}/2 essentials ready</p><div className="h-1.5 bg-white/20 rounded-full mt-3"><div className="h-full bg-white rounded-full" style={{width:`${[ready.skills,ready.goal].filter(Boolean).length*50}%`}}/></div></div><nav className="p-2.5">{NAV.map(item=>{const Icon=item.icon;const selected=section===item.key;const complete=item.key==="skills"?ready.skills:item.key==="goal"?ready.goal:item.key==="resume"?ready.resume:false;return <button key={item.key} onClick={()=>setSection(item.key)} className={`w-full flex items-center gap-3 px-3 py-3 rounded-xl text-left mb-1 transition-all ${selected?"bg-[#EBF1FA]":"hover:bg-[#F4F7FC]"}`}><div className={`w-8 h-8 rounded-lg flex items-center justify-center ${selected?"bg-[#1B3A6B]":"bg-[#EFF2FA]"}`}><Icon size={14} className={selected?"text-white":"text-[#5A6A8A]"}/></div><div className="flex-1"><p className={`text-[12px] font-semibold ${selected?"text-[#1B3A6B]":"text-[#0F1C3F]"}`}>{item.label}</p><p className="text-[10.5px] text-[#9AA5BE]">{item.desc}</p></div>{complete?<Check size={13} className="text-emerald-600"/>:selected?<ChevronRight size={13} className="text-[#1B3A6B]"/>:null}</button>})}</nav></div></aside>
      <main className="bg-white rounded-2xl border border-[--border] shadow-sm overflow-hidden"><div className="px-8 py-5 border-b border-[--border] flex items-center gap-4"><div className="w-11 h-11 rounded-xl bg-[#1B3A6B] flex items-center justify-center"><active.icon size={19} className="text-white"/></div><div><h1 className="text-[19px] text-[#0F1C3F]" style={{fontFamily:"var(--font-serif)"}}>{active.label}</h1><p className="text-[12.5px] text-[#5A6A8A]">{active.desc}</p></div>{section==="roadmap"&&<span className="ml-auto flex items-center gap-1 text-[10.5px] text-amber-700 bg-amber-50 px-2.5 py-1 rounded-full"><Sparkles size={10}/>AI-powered</span>}</div><div className="px-8 py-7">{section==="skills"?<SkillsView onReady={()=>setReady(x=>({...x,skills:true}))}/>:section==="goal"?<GoalView onReady={()=>setReady(x=>({...x,goal:true}))}/>:section==="resume"?<ResumeView onReady={()=>setReady(x=>({...x,resume:true}))}/>:section==="roadmap"?<RoadmapView readiness={ready} onEnroll={()=>setCourseRefresh(x=>x+1)}/>:<CoursesView refresh={courseRefresh} onOpen={id=>loadEnrolledCourse(id).then(setPlaying)}/>}</div></main></div></div>;
}
